export type InputProps = {
  height?: number;
  placeholder?: string;
  style?: any;
  text?: string;
  value?: any;
  onChangeText?: any;
  secureTextEntry?: any;
  keyboardType?: string;
  backgroundColor?: string;
  label?: string;
  error?: string;
  theme?: any;
  editable?: boolean;
  marginTop?: number;
  visible?: any;
  onDismiss?: any;
  showDropDown?: any;
  setValue?: any;
  list?: any;
  dropDownStyle?: any;
  labelStyle?: any;
  selectedTextStyle?: any;
  placeholderStyle?: any;
  inputSearchStyle?: any;
  data?: any;
  iconStyle?: any;
  labelField?: string;
  valueField?: any;
  onChange?: any;
  maxHeight?: number;
  onFocus?: any;
  labelColor?: string;
  maxLength?: number;
  onPress?: any;
  searchPlaceholder?: string;
  isChecked?: boolean;
};
export type OptionType = {
  _index: number;
  label: string;
  value: string;
};