export type InputProps = {
  height?: number;
  placeholder?: string;
  style?: any;
  value?: any;
  onChangeText?: any;
  secureTextEntry?: any;
  keyboardType?: string;
  backgroundColor?: string;
  label?: string;
  error?: string;
  theme?: any;
  editable?: boolean;
  marginTop?: number;
  visible?: any;
  onDismiss?: any;
  showDropDown?: any;
  setValue?: any;
  list?: any;
  dropDownStyle?: any;
};
