pipelines:
  branches:
    develop:
      - step:
          name: Install Node modules
          image: node:18
          script:
            - npm install
      - step:
          name: Install CocoaPods
          image: node:18
          script:
            # Install CocoaPods
            - gem install cocoapods
      - step:
          name: Install CocoaPods dependencies and Fastlane
          image: ruby:latest
          script:
            # Navigate to iOS directory and run pod install
            - cd ios && pod install
            # Install Homebrew if not already installed
            - command -v brew || /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
            # Install Ruby dependencies for Fastlane
            - gem install bundler
            # Install Fastlane 123
            - gem install fastlane
      - step: 
          name: Make build and release to testflight
          script:
            - npm run ios:beta
