pipelines:
  branches:
    develop:
      - step:
          name: Install Node modules
          image: node:18
          script:
            - npm install
      - step:
          name: Install RubyGems and CocoaPods
          image: ruby:latest
          script:
            # Install RubyGems
            - apt-get update && apt-get install -y rubygems
            # Install CocoaPods
            - gem install cocoapods
      - step:
          name: Install CocoaPods dependencies and Fastlane
          image: ruby:latest
          script:
            - gem install bundler
            # Install Fastlane
            - gem install fastlane
            # Set up PATH
            - export PATH="$HOME/.fastlane/bin:$PATH"
      - step: 
          name: Make build and release to testflight
          script:
            # - npm run ios:beta
            - fastlane beta
