import { NativeSyntheticEvent, TextInputSubmitEditingEventData } from 'react-native';
import React from 'react';
import { ImageType } from '../shared/helper/types';
import { BorderStyleInterface, FontStyleInterface } from '../shared';
export declare function Header(props: {
    backButtonIcon?: ImageType;
    showBackButton?: boolean;
    onBack?: () => void;
    title?: string;
    AppBarOptions?: () => JSX.Element;
    shouldSelect?: boolean;
    onSelectionHandler?: () => void;
    hideSearch?: boolean;
    searchBoxIcon?: ImageType;
    searchPlaceholderText?: string;
    searchPlaceholderTextColor?: string;
    searchHandler?: (text: string) => void;
    searchInput?: string;
    onSubmitEditing?: (e: NativeSyntheticEvent<TextInputSubmitEditingEventData>) => void;
    selectionIcon?: ImageType;
    titleFontStyle?: FontStyleInterface;
    titleColor?: string;
    backIconTint?: string;
    searchBorderStyle?: BorderStyleInterface;
    searchBorderRadius?: number;
    searchTextFontStyle?: FontStyleInterface;
    searchTextColor?: string;
    searchIconTint?: string;
    searchBackgroundColor?: string;
    selectionIconTint?: string;
}): React.JSX.Element;
