export const genderArray = [
  'Male',
  'Female',
  'Transman',
  'Transwoman',
  'Non-binary',
];
export const genderPronounArray = [
  'He/Him',

  'She/Her',

  'They/Them',

  'Prefer not to say',
];
export const sexualOrientationArray = [
  'Straight',
  'Gay',
  'Lesbian',
  'Bisexual',
  'Pansexual',
  'Queer',
  'Questioning',
  'Asexual',
  'Demisexual',
];

export const country = [
  { label: 'USA', value: 'USA' },
  { label: 'Canada', value: 'Canada' },
];

export const statesOption: { USA: string[]; Canada: string[] } = {
  USA: [
    'Alabama (AL)',
    'Alaska (AK)',
    'American Samoa',
    'Arizona (AZ)',
    'Arkansas (AR)',
    'California (CA)',
    'Colorado (CO)',
    'Connecticut (CT)',
    'Delaware (DE)',
    'District of Columbia (DC)',
    'Florida (FL)',
    'Georgia (GA)',
    'Guam',
    'Hawaii (HI)',
    'Idaho (ID)',
    'Illinois (IL)',
    'Indiana (IN)',
    'Iowa (IA)',
    'Kansas (KS)',
    'Kentucky (KY)',
    'Louisiana (LA)',
    'Maine (ME)',
    'Maryland (MD)',
    'Massachusetts (MA)',
    'Michigan (MI)',
    'Minnesota (MN)',
    'Mississipi (MS)',
    'Missouri (MO)',
    'Montana (MT)',
    'Nebraska (NE)',
    'Nevada (NV)',
    'New Hampshire (NH)',
    'New Jersey (NJ)',
    'New Mexico (NM)',
    'New York (NY)',
    'Northern Mariana Islands',
    'North Carolina (NC)',
    'North Dakota (ND)',
    'Ohio (OH)',
    'Oklahoma (OK)',
    'Oregon (OR)',
    'Pennsylvania (PA)',
    'Puerto Rico',
    'Rhode Island (RI)',
    'South Carolina (SC)',
    'South Dakota (SD)',
    'Tennessee (TN)',
    'Texas (TX)',
    'US Virgin Islands',
    'Utah (UT)',
    'Vermont (VT)',
    'Virginia (VA)',
    'Washington (WA)',
    'West Virginia (WV)',
    'Wisconsin (WI)',
  ],

  Canada: [
    'Alberta',
    'British Columbia',
    'Manitoba',
    'New Brunswick',
    'Newfoundland and Labrador',
    'Northwest Teritories',
    'Nova Scotia',
    'Nunavut',
    'Ontario',
    'Prince Edward Island',
    'Quebec',
    'Saskatchewan',
    'Yukon',
  ],
};

export const userDegree = [
  {
    label: 'Healthcare Doctorate Degree',
    value: 'Healthcare Doctorate Degree',
  },
  {
    label: 'Healthcare Doctorate Student',
    value: 'Healthcare Doctorate Student',
  },
  {
    label: 'PhD in Health-Related Field',
    value: 'PhD in Health-Related Field',
  },
  {
    label: 'Doctoral Student in Health-Related Field',
    value: 'Doctoral Student in Health-Related Field',
  },
  { label: 'Healthcare Master’s Degree', value: 'Healthcare Master’s Degree' },
  {
    label: 'Healthcare Master’s Student',
    value: 'Healthcare Master’s Student',
  },
];

export const primaryDegree = {
  'Healthcare Doctorate Degree': [
    'Doctor of Acupuncture (DAc)',
    'Doctor of Athletic Training (DAT)',
    'Doctor of Audiology (AuD)',
    'Doctor of Behavioral Health (DBH)',
    'Doctor of Chemistry (DChem)',
    'Doctor of Chiropractic Medicine (DC)',
    'Doctor of Clinical Laboratory Science (DCLS)',
    'Doctor of Professional Counseling (DPC)',
    'Doctor of Dental Surgery/Dental Medicine (DDS/DMD)',
    'Doctor of Health and Safety (DHS)',
    'Doctor of Healthcare Administration (DHA)',
    'Doctor of Health Science (DHSc/DHS)',
    'Doctor of Medical Physics (DMP)',
    'Doctor of Medicine (MD)',
    'Doctor of Naturopathic Medicine (ND/NMD)',
    'Doctor of Nursing Practice (DNP)',
    'Doctor of Nursing Science (DNSc)',
    'Doctor of Nurse Anesthesia Practice (DNAP)',
    'Doctor of Occupational Therapy (DOT)',
    'Doctor of Optometry (OD)',
    'Doctor of Osteopathic Medicine (DO)',
    'Doctor of Pharmacy (PharmD)',
    'Doctor of Physical Therapy (DPT)',
    'Doctor of Podiatric Medicine (DPM)',
    'Doctor of Psychology (DPsy/PsyD)',
    'Doctor of Public Health (DrPH)',
    'Doctor of Social Work (DSW)',
    'Doctor of Speech-Language Pathology (DSLP)',
    'Doctor of Veterinary Medicine (DVM/VMD)',
  ],

  'Healthcare Doctorate Student': [
    'Student of Acupuncture (DAc)',
    'Student of Athletic Training (DAT)',
    'Student of Audiology (AuD)',
    'Student of Behavioral Health (DBH)',
    'Student of Chemistry (DChem)',
    'Student of Chiropractic Medicine (DC)',
    'Student of Clinical Laboratory Science (DCLS)',
    'Student of Professional Counseling (DPC)',
    'Student of Dental Surgery/Dental Medicine (DDS/DMD)',
    'Student of Health and Safety (DHS)',
    'Student of Healthcare Administration (DHA)',
    'Student of Health Science (DHSc/DHS)',
    'Student of Medical Physics (DMP)',
    'Student of Medicine (MD)',
    'Student of Naturopathic Medicine (ND/NMD)',
    'Student of Nursing Practice (DNP)',
    'Student of Nursing Science (DNSc)',
    'Student of Nurse Anesthesia Practice (DNAP)',
    'Student of Occupational Therapy (DOT)',
    'Student of Optometry (OD)',
    'Student of Osteopathic Medicine (DO)',
    'Student of Pharmacy (PharmD)',
    'Student of Physical Therapy (DPT)',
    'Student of Podiatric Medicine (DPM)',
    'Student of Psychology (DPsy/PsyD)',
    'Student of Public Health (DrPH)',
    'Student of Social Work (DSW)',
    'Student of Speech-Language Pathology (DSLP)',
    'Student of Veterinary Medicine (DVM/VMD)',
  ],

  'PhD in Health-Related Field': [
    'PhD Audiology',
    'PhD Biochemistry',
    'PhD Biochemical Engineering',
    'PhD Biology',
    'PhD Biomedical Engineering',
    'PhD Biomedical Science',
    'PhD Bioscience',
    'PhD Chemical Engineering',
    'PhD Chemistry',
    'PhD Genetics',
    'PhD Healthcare Administration',
    'PhD Immunology',
    'PhD Kinesiology',
    'PhD Microbiology',
    'PhD Molecular Biology',
    'PhD Neuroscience',
    'PhD Nursing Education',
    'PhD Nutrition',
    'PhD Occupational and Environmental Health',
    'PhD Pharmacology',
    'PhD Physiology',
    'PhD Physics',
    'PhD Psychology',
    'PhD Public Health',
    'PhD degree with health focus',
  ],

  'Doctoral Student in Health-Related Field': [
    'PhD Audiology',
    'PhD Biochemistry',
    'PhD Biochemical Engineering',
    'PhD Biology',
    'PhD Biomedical Engineering',
    'PhD Biomedical Science',
    'PhD Bioscience',
    'PhD Chemical Engineering',
    'PhD Chemistry',
    'PhD Genetics',
    'PhD Healthcare Administration',
    'PhD Immunology',
    'PhD Kinesiology',
    'PhD Microbiology',
    'PhD Molecular Biology',
    'PhD Neuroscience',
    'PhD Nursing Education',
    'PhD Nutrition',
    'PhD Occupational and Environmental Health',
    'PhD Pharmacology',
    'PhD Physiology',
    'PhD Physics',
    'PhD Psychology',
    'PhD Public Health',
  ],

  'Healthcare Master’s Degree': [
    'Advanced Practice Registered Nurse (APRN)/Nurse Practitioner (NP)',
    'Master of Counseling (MC)',
    'Master of Dental Science (MDS)',
    'Master of Health/Healthcare Administration (MHA)',
    'Master of Health Science (MHS)',
    'Master of Science Medical Physics (MSMP)',
    'Master of Marriage and Family Therapy (MFT)',
    'Master of Science Nursing (MSN)',
    'Master of Science Clinical Nutrition/Dietician (MSCN/RD/RDN)',
    'Master of Public Health (MPH)',
    'Master of Psychology (MPsych)',
    'Master of Science Respiratory Care (MSRC)',
    'Master of Social Work (MSW)',
    'Master of Occupational Therapy (OT)',
    'Master of Physical Therapy (MPT)',
    'Master of Physician Assistant Studies (PA)',
    'Master of Speech Therapy (ST)',
    'Master Veterinary Science (MVSC)',
  ],

  'Healthcare Master’s Student': [
    'Student of Advanced Practice Registered Nurse (APRN)/Nurse Practitioner (NP)',
    'Student of Master of Counseling (MC)',
    'Student of Master of Dental Science (MDS)',
    'Student of Master of Health/Healthcare Administration (MHA)',
    'Student of Master of Health Science (MHS)',
    'Student of Master of Science Medical Physics (MSMP)',
    'Student of Master of Marriage and Family Therapy (MFT)',
    'Student of Master of Science Nursing (MSN)',
    'Student of Master of Science Clinical Nutrition/Dietician (MSCN/RD/RDN)',
    'Student of Master of Public Health (MPH)',
    'Student of Master of Psychology (MPsych)',
    'Student of Master of Science Respiratory Care (MSRC)',
    'Student of Master of Social Work (MSW)',
    'Student of Master of Occupational Therapy (OT)',
    'Student of Master of Physician Assistant Studies (PA)',
    'Student of Master of Speech Therapy (ST)',
    'Student of Master Veterinary Science (MVSC)',
  ],
};
