export const genderArray = [
  'Man',
  'Woman',
  'Trans-Man',
  'Trans-Woman',
  'Non-Binary',
  'Everyone',
];
export const genderPronounArray = [
  'He/Him',
  'She/Her',
  'They/Them',
  'Prefer not to say',
];

export const maritalStatus = [
  'Never Married',
  'Divorced',
  'Annulled',
  'Separated',
  'Widowed',
  'Complicated',
  'Prefer not to say',
];

export const religion = [
  'Buddhist',
  'Christian',
  'Hindu',
  'Catholic',
  'Jewish',
  'Muslim',
  'Sikh',
  'Shinto',
  'Taoism',
  'Spiritual',
  'Agnostic',
  'Atheist',
  'Other',
  'Prefer not to say',
];

export const hobbies = [
  'Art',
  'Camping',
  'Cooking',
  'Cultures',
  'Concerts/festival',
  'Dancing',
  'DIY',
  'Fitness',
  'Foodie',
  'Gardening',
  'Hiking',
  'Languages',
  'Listening to music',
  'Meditation',
  'Movies',
  'Playing sports',
  'Photography',
  'Poetry',
  'Reading',
  'Running',
  'Swimming',
  'Shopping',
  'Social causes',
  'Traveling',
  'TV shows',
  'Volunteering',
  'Watching sports',
  'Writing',
  'Video games',
];

export const smoking = [
  'Never',
  'Rarely',
  'Sometimes',
  'Frequently',
  'Prefer not to say',
];

export const exercise = [
  'Never',
  'Rarely',
  'Sometimes',
  'Frequently',
  'Prefer not to say',
];

export const politics = [
  'Conservative',
  'Moderate',
  'Liberal',
  'Non-Political',
  'Prefer not to say',
];

export const diet = [
  'No restrictions',
  'Gluten-free',
  'Vegetarian',
  'Vegan',
  'Pescatarian',
  'Halal',
  'Kosher',
  'Other',
  'Prefer not to say',
];

export const drinking = [
  'Never',
  'Rarely',
  'Sometimes',
  'Frequently',
  'Prefer not to say',
];

export const kids = ['None', 'Have kids', 'Prefer not to say'];

export const familyPlan = [
  'Open to kids',
  'Want kids',
  "Don't want kids",
  'Undecided',
  'Prefer not to say',
];

export const pets = [
  'None',
  'Cats',
  'Dogs',
  'Both',
  'Other pets',
  'Prefer not to say',
];

export const cannabis = [
  'Never',
  'Rarely',
  'Sometimes',
  'Frequently',
  'Prefer not to say',
];

export const covidVaccineStatus = [
  'Fully',
  'Partially',
  'Unable to receive',
  'Decline',
  'Prefer not to say',
];

export const sexualOrientationArray = [
  'Straight',
  'Gay',
  'Lesbian',
  'Bisexual',
  'Pansexual',
  'Queer',
  'Questioning',
  'Asexual',
  'Demisexual',
  'Non-Binary',
];

export const country = [
  { label: 'USA', value: 'USA' },
  { label: 'Canada', value: 'Canada' },
];

export const relationship = [
  'Long-term relationship',
  'Long-term relationship, open to short-term',
  'Short-term relationship, open to long-term',
  'Casual',
  'Friendship',
  'Marriage',
  'Prefer not to say',
];

export const ethnicity = [
  'American Indian or Alaska Native',
  'East Asian',
  'South Asian',
  'Southeast Asian',
  'Black or African American',
  'Middle Eastern',
  'Hispanic or Latino',
  'Native Hawaiian or Pacific Island',
  'White or Caucasian',
  'Other',
  'Prefer not to say',
];

export const preferNotToSay = 'Prefer not to say';

export const statesOption: any = {
  USA: [
    'Alabama (AL)',
    'Alaska (AK)',
    'American Samoa',
    'Arizona (AZ)',
    'Arkansas (AR)',
    'California (CA)',
    'Colorado (CO)',
    'Connecticut (CT)',
    'Delaware (DE)',
    'District of Columbia (DC)',
    'Florida (FL)',
    'Georgia (GA)',
    'Guam',
    'Hawaii (HI)',
    'Idaho (ID)',
    'Illinois (IL)',
    'Indiana (IN)',
    'Iowa (IA)',
    'Kansas (KS)',
    'Kentucky (KY)',
    'Louisiana (LA)',
    'Maine (ME)',
    'Maryland (MD)',
    'Massachusetts (MA)',
    'Michigan (MI)',
    'Minnesota (MN)',
    'Mississipi (MS)',
    'Missouri (MO)',
    'Montana (MT)',
    'Nebraska (NE)',
    'Nevada (NV)',
    'New Hampshire (NH)',
    'New Jersey (NJ)',
    'New Mexico (NM)',
    'New York (NY)',
    'Northern Mariana Islands',
    'North Carolina (NC)',
    'North Dakota (ND)',
    'Ohio (OH)',
    'Oklahoma (OK)',
    'Oregon (OR)',
    'Pennsylvania (PA)',
    'Puerto Rico',
    'Rhode Island (RI)',
    'South Carolina (SC)',
    'South Dakota (SD)',
    'Tennessee (TN)',
    'Texas (TX)',
    'US Virgin Islands',
    'Utah (UT)',
    'Vermont (VT)',
    'Virginia (VA)',
    'Washington (WA)',
    'West Virginia (WV)',
    'Wisconsin (WI)',
  ],

  Canada: [
    'Alberta, (AB)',
    'British Columbia, (BC)',
    'Manitoba,(MB) ',
    'New Brunswick, (NB)',
    'Newfoundland and Labrador, (NL)',
    'Northwest Teritories, (NT)',
    'Nova Scotia, (NS)',
    'Nunavut, (NU)',
    'Ontario, (ON)',
    'Prince Edward Island, (PE)',
    'Quebec, (QB)',
    'Saskatchewan, (SK)',
    'Yukon. (YT)',
  ],
};

export const userDegree = [
  {
    label: 'Healthcare Doctorate Degree',
    value: 'Healthcare Doctorate Degree',
  },
  {
    label: 'Healthcare Doctorate Student',
    value: 'Healthcare Doctorate Student',
  },
  {
    label: 'PhD in Health-Related Field',
    value: 'PhD in Health-Related Field',
  },
  {
    label: 'Doctoral Student in Health-Related Field',
    value: 'Doctoral Student in Health-Related Field',
  },
  {
    label: 'Healthcare Master’s Degree',
    value: 'Healthcare Master’s Degree',
  },
  {
    label: 'Healthcare Master’s Student',
    value: 'Healthcare Master’s Student',
  },
];

export const primaryDegree: any = {
  'Healthcare Doctorate Degree': [
    'Doctor of Acupuncture - (DAc)',
    'Doctor of Athletic Training - (DAT)',
    'Doctor of Audiology - (AuD)',
    'Doctor of Behavioral Health - (DBH)',
    'Doctor of Chemistry - (DChem)',
    'Doctor of Chiropractic Medicine - (DC)',
    'Doctor of Clinical Laboratory Science - (DCLS)',
    'Doctor of Professional Counseling - (DPC)',
    'Doctor of Dental Surgery/Dental Medicine - (DDS/DMD)',
    'Doctor of Health and Safety - (DHS)',
    'Doctor of Healthcare Administration - (DHA)',
    'Doctor of Health Science - (DHSc/DHS)',
    'Doctor of Medical Physics - (DMP)',
    'Doctor of Medicine - (MD)',
    'Doctor of Naturopathic Medicine - (ND/NMD)',
    'Doctor of Nursing Practice - (DNP)',
    'Doctor of Nursing Science - (DNSc)',
    'Doctor of Nurse Anesthesia Practice - (DNAP)',
    'Doctor of Occupational Therapy - (DOT)',
    'Doctor of Optometry - (OD)',
    'Doctor of Osteopathic Medicine - (DO)',
    'Doctor of Pharmacy - (PharmD)',
    'Doctor of Physical Therapy - (DPT)',
    'Doctor of Podiatric Medicine - (DPM)',
    'Doctor of Psychology - (DPsy/PsyD)',
    'Doctor of Public Health - (DrPH)',
    'Doctor of Social Work - (DSW)',
    'Doctor of Speech-Language Pathology - (DSLP)',
    'Doctor of Veterinary Medicine - (DVM/VMD)',
  ],

  'Healthcare Doctorate Student': [
    'Student of Acupuncture - (DAc)',
    'Student of Athletic Training - (DAT)',
    'Student of Audiology - (AuD)',
    'Student of Behavioral Health - (DBH)',
    'Student of Chemistry - (DChem)',
    'Student of Chiropractic Medicine - (DC)',
    'Student of Clinical Laboratory Science - (DCLS)',
    'Student of Professional Counseling - (DPC)',
    'Student of Dental Surgery/Dental Medicine - (DDS/DMD)',
    'Student of Health and Safety - (DHS)',
    'Student of Healthcare Administration - (DHA)',
    'Student of Health Science - (DHSc/DHS)',
    'Student of Medical Physics - (DMP)',
    'Student of Medicine - (MD)',
    'Student of Naturopathic Medicine - (ND/NMD)',
    'Student of Nursing Practice - (DNP)',
    'Student of Nursing Science - (DNSc)',
    'Student of Nurse Anesthesia Practice - (DNAP)',
    'Student of Occupational Therapy - (DOT)',
    'Student of Optometry - (OD)',
    'Student of Osteopathic Medicine - (DO)',
    'Student of Pharmacy - (PharmD)',
    'Student of Physical Therapy - (DPT)',
    'Student of Podiatric Medicine - (DPM)',
    'Student of Psychology - (DPsy/PsyD)',
    'Student of Public Health - (DrPH)',
    'Student of Social Work - (DSW)',
    'Student of Speech-Language Pathology - (DSLP)',
    'Student of Veterinary Medicine - (DVM/VMD)',
  ],

  'PhD in Health-Related Field': [
    'PhD Audiology - (AuD)',
    'PhD Biochemistry - (PhD Biochem)',
    'PhD Biochemical Engineering - (PhD BMEN)',
    'PhD Biology - (PhD Biol)',
    'PhD Biomedical Engineering - (PhD BME)',
    'PhD Biomedical Science - (PhD BMS)',
    'PhD Bioscience - (PhD Biosci)',
    'PhD Chemical Engineering - (PhD ChemE)',
    'PhD Chemistry - (PhD Chem)',
    'PhD Genetics - (PhD Genet)',
    'PhD Healthcare Administration - (PhD HA)',
    'PhD Immunology - (PhD Immunol)',
    'PhD Kinesiology - (PhD Kinesiol)',
    'PhD Microbiology - (PhD Microbiol)',
    'PhD Molecular Biology - (PhD Mol Biol)',
    'PhD Neuroscience - (PhD Neurosci)',
    'PhD Nursing Education - (PhD Nurs Ed)',
    'PhD Nutrition - (PhD Nutr)',
    'PhD Occupational and Environmental Health - (PhD OEH)',
    'PhD Pharmacology - (PhD Pharmacol)',
    'PhD Physiology - (PhD Physiol)',
    'PhD Physics - (PhD Phys)',
    'PhD Psychology - (PhD Psych)',
    'PhD Public Health - (DrPH)',
    'PhD degree with Health Focus - (PhD Health Focus)',
  ],

  'Doctoral Student in Health-Related Field': [
    'PhD Audiology - (AuD Student)',
    'PhD Biochemistry - (PhD Biochem Student)',
    'PhD Biochemical Engineering - (PhD BMEN Student)',
    'PhD Biology - (PhD Biol Student)',
    'PhD Biomedical Engineering - (PhD BME Student)',
    'PhD Biomedical Science - (PhD BMS Student)',
    'PhD Bioscience - (PhD Biosci Student)',
    'PhD Chemical Engineering - (PhD ChemE Student)',
    'PhD Chemistry - (PhD Chem Student)',
    'PhD Genetics - (PhD Genet Student)',
    'PhD Healthcare Administration - (PhD HA Student)',
    'PhD Immunology - (PhD Immunol Student)',
    'PhD Kinesiology - (PhD Kinesiol Student)',
    'PhD Microbiology - (PhD Microbiol Student)',
    'PhD Molecular Biology - (PhD Mol Biol Student)',
    'PhD Neuroscience - (PhD Neurosci Student)',
    'PhD Nursing Education - (PhD Nurs Ed Student)',
    'PhD Nutrition - (PhD Nutr Student)',
    'PhD Occupational and Environmental Health - (PhD OEH Student)',
    'PhD Pharmacology - (PhD Pharmacol Student)',
    'PhD Physiology - (PhD Physiol Student)',
    'PhD Physics - (PhD Phys Student)',
    'PhD Psychology - (PhD Psych Student)',
    'PhD Public Health - (DrPH Student)',
    'PhD degree with Health Focus - (PhD Health Focus Student)',
  ],

  'Healthcare Master’s Degree': [
    'Advanced Practice Registered Nurse - (APRN)/Nurse Practitioner - (NP)',
    'Master of Counseling - (MC)',
    'Master of Dental Science - (MDS)',
    'Master of Health/Healthcare Administration - (MHA)',
    'Master of Health Science - (MHS)',
    'Master of Science Medical Physics - (MSMP)',
    'Master of Marriage and Family Therapy - (MFT)',
    'Master of Science Nursing - (MSN)',
    'Master of Science Clinical Nutrition/Dietician - (MSCN/RD/RDN)',
    'Master of Public Health - (MPH)',
    'Master of Psychology - (MPsych)',
    'Master of Science Respiratory Care - (MSRC)',
    'Master of Social Work - (MSW)',
    'Master of Occupational Therapy - (OT)',
    'Master of Physical Therapy - (MPT)',
    'Master of Physician Assistant Studies - (PA)',
    'Master of Speech Therapy - (ST)',
    'Master Veterinary Science - (MVSC)',
  ],

  'Healthcare Master’s Student': [
    'Student of Advanced Practice Registered Nurse - (APRN)/Nurse Practitioner - (NP)',
    'Student of Master of Counseling - (MC)',
    'Student of Master of Dental Science - (MDS)',
    'Student of Master of Health/Healthcare Administration - (MHA)',
    'Student of Master of Health Science - (MHS)',
    'Student of Master of Science Medical Physics - (MSMP)',
    'Student of Master of Marriage and Family Therapy - (MFT)',
    'Student of Master of Science Nursing - (MSN)',
    'Student of Master of Science Clinical Nutrition/Dietician - (MSCN/RD/RDN)',
    'Student of Master of Public Health - (MPH)',
    'Student of Master of Psychology - (MPsych)',
    'Student of Master of Science Respiratory Care - (MSRC)',
    'Student of Master of Social Work - (MSW)',
    'Student of Master of Occupational Therapy - (OT)',
    'Student of Master of Physician Assistant Studies - (PA)',
    'Student of Master of Speech Therapy - (ST)',
    'Student of Master Veterinary Science - (MVSC)',
  ],
};

export const degreeIdentifierType = [
  'CPSO',
  'CNO',
  'MINC',
  'MSP',
  'Licence',
  'Registration',
  'Permit',
  'Training Card Number',
  'Other Identifier',
];
export const minFeetValues = [
  `3'0"`,
  `3'1"`,
  `3'2"`,
  `3'3"`,
  `3'4"`,
  `3'5"`,
  `3'6"`,
  `3'7"`,
  `3'8"`,
  `3'9"`,
  `3'10"`,
  `3'11"`,
  `4'0"`,
  `4'1"`,
  `4'2"`,
  `4'3"`,
  `4'4"`,
  `4'5"`,
  `4'6"`,
  `4'7"`,
  `4'8"`,
  `4'9"`,
  `4'10"`,
  `4'11"`,
  `5'0"`,
  `5'1"`,
  `5'2"`,
  `5'3"`,
  `5'4"`,
  `5'5"`,
  `5'6"`,
  `5'7"`,
  `5'8"`,
  `5'9"`,
  `5'10"`,
  `5'11"`,
  `6'0"`,
  `6'1"`,
  `6'2"`,
  `6'3"`,
  `6'4"`,
  `6'5"`,
  `6'6"`,
  `6'7"`,
  `6'8"`,
  `6'9"`,
  `6'10"`,
  `6'11"`,
  `7'0"`,
];
export const feetValues = [
  `3'0"`,
  `3'1"`,
  `3'2"`,
  `3'3"`,
  `3'4"`,
  `3'5"`,
  `3'6"`,
  `3'7"`,
  `3'8"`,
  `3'9"`,
  `3'10"`,
  `3'11"`,
  `4'0"`,
  `4'1"`,
  `4'2"`,
  `4'3"`,
  `4'4"`,
  `4'5"`,
  `4'6"`,
  `4'7"`,
  `4'8"`,
  `4'9"`,
  `4'10"`,
  `4'11"`,
  `5'0"`,
  `5'1"`,
  `5'2"`,
  `5'3"`,
  `5'4"`,
  `5'5"`,
  `5'6"`,
  `5'7"`,
  `5'8"`,
  `5'9"`,
  `5'10"`,
  `5'11"`,
  `6'0"`,
  `6'1"`,
  `6'2"`,
  `6'3"`,
  `6'4"`,
  `6'5"`,
  `6'6"`,
  `6'7"`,
  `6'8"`,
  `6'9"`,
  `6'10"`,
  `6'11"`,
  `7'0"`,
  `7'1"`,
  `7'2"`,
  `7'3"`,
  `7'4"`,
  `7'5"`,
  `7'6"`,
  `7'7"`,
  `7'8"`,
  `7'9"`,
  `7'10"`,
  `7'11"`,
  `8'0"`,
];

export const options = [
  { label: 'Feet', value: 'feet' },
  { label: 'Cm', value: 'cm' },
];
export const cmValues = feetValues.map((height) => {
  const [feet, inches] = height.split("'");
  const totalInches = parseInt(feet) * 12 + parseInt(inches.replace('"', ''));
  const totalCm = totalInches * 2.54;
  return Math.round(totalCm);
});
export const mincmValues = minFeetValues.map((height) => {
  const [feet, inches] = height.split("'");
  const totalInches = parseInt(feet) * 12 + parseInt(inches.replace('"', ''));
  const totalCm = totalInches * 2.54;
  return Math.round(totalCm);
});
export const report = [
  'Fake account',
  'Spam',
  'Abusive or threatening behavior',
  'Racism, discrimination, or insults',
  'Contains illegal content or activity',
  'Other',
];
export const noPreference = 'No preference';
