export declare const ICONS: {
    EDIT: any;
    DELETE: any;
    COPY: any;
    SHARE: any;
    INFO: any;
    THREAD: any;
    REPLY: any;
    HEART: any;
    SEND: any;
    EMOJI: any;
    ADD: any;
    AUDIO: any;
    IMAGE: any;
    VIDEO: any;
    FILE: any;
    PRIVATE_MESSAGE: any;
    PLAY: any;
    PAUSE: any;
    STOP_PLAYER: any;
    MICROPHONE: any;
};
