declare const ExtensionConstants: {
    extensions: string;
    linkPreview: string;
    smartReply: string;
    messageTranslation: string;
    profanityFilter: string;
    imageModeration: string;
    thumbnailGeneration: string;
    sentimentalAnalysis: string;
    polls: string;
    reactions: string;
    whiteboard: string;
    document: string;
    dataMasking: string;
    stickers: string;
    xssFilter: string;
    saveMessage: string;
    pinMessage: string;
    voiceTranscription: string;
    richMedia: string;
    malwareScanner: string;
    mentions: string;
    customStickers: string;
    defaultStickers: string;
    stickerUrl: string;
    sanitizedText: string;
    hasXSS: string;
    yes: string;
    post: string;
    data: string;
    sensitiveData: string;
    messageMasked: string;
    profanity: string;
    messageClean: string;
};
declare const ExtensionURLs: {
    reaction: string;
    stickers: string;
    document: string;
    whiteboard: string;
    translate: string;
    poll: string;
};
declare const ExtensionTypeConstants: {
    extensionPoll: string;
    sticker: string;
    document: string;
    whiteboard: string;
};
export { ExtensionConstants, ExtensionURLs, ExtensionTypeConstants };
